spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: sso-client-2
            client-secret: 5f26da8a-843e-4a22-a825-a552080158af
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/ui-two/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8080/auth/realms/bcp/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/bcp/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/bcp/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8082
  servlet: 
    context-path: /ui-two

resourceserver:
  api:
    url:
      foo: http://localhost:9091/sso-resource-server/api/foos/
      userinfo: http://localhost:9091/sso-resource-server/user/info
              
logging: 
  level: 
    '[org.springframework]': INFO