spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: sso-client-1
            client-secret: 813a9cb2-6e27-4cc4-898d-147cb99bf025
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/ui-one/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8080/auth/realms/bcp/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/bcp/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/bcp/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8081
  servlet: 
    context-path: /ui-one

resourceserver:
  api:
    url: http://localhost:9091/sso-resource-server/api/foos/
              
logging: 
  level: 
    '[org.springframework]': INFO