spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: sso-client-1
            client-secret: g2nFKRacSGONedOoL7HUT6Cgc3cza84a
            scope: read,write,openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/ui-one/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bcp
            authorization-uri: http://localhost:8080/realms/bcp/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/bcp/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/bcp/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8081
  servlet: 
    context-path: /ui-one

resourceserver:
  api:
    url:
      foo: http://localhost:9091/sso-resource-server/api/foos/
      userinfo: http://localhost:9091/sso-resource-server/user/info
              
logging: 
  level: 
    '[org.springframework]': INFO